---
title: "Getting started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{getting_started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(flexdashboard)
library(kpiwidget)
```

```{r}
library(crosstalk)
library(dplyr)
library(htmltools)

# Example data
df <- mtcars %>% 
  mutate(model = rownames(.))

# Wrap in SharedData with row numbers as keys
sd <- SharedData$new(df, key = ~1:nrow(df), group = "mtcars_group")
```

<div>&nbsp;</div>

```{r}
filter_checkbox("gear", "Gear", sd, ~gear, inline = TRUE)
```

<div>&nbsp;</div>

Column parameter must be provided. Default kpi is `count` (lenght of dataset).
```{r}
kpiwidget(
  data = sd,
  column = "mpg")
```

<div>&nbsp;</div>

## KPI options

### sum
```{r}
kpiwidget(
  data = sd,
  column = "mpg",
  kpi = "sum",
  height = "50px")
```

### mean
```{r}
kpiwidget(
  data = sd,
  column = "mpg",
  kpi = "mean",
  height = "50px")
```

### min
```{r}
kpiwidget(
  data = sd,
  column = "mpg",
  kpi = "min",
  height = "50px")
```

### max
```{r}
kpiwidget(
  data = sd,
  column = "mpg",
  kpi = "max",
  height = "50px")
```

### count
```{r}
kpiwidget(
  data = sd,
  column = "mpg",
  kpi = "count",
  height = "50px")
```

### distinctCount
```{r}
kpiwidget(
  data = sd,
  column = "cyl",
  kpi = "distinctCount",
  height = "50px")
```

### ratio
```{r}
kpiwidget(
  data = sd,
  column = "mpg",
  kpi = "sum",
  comparison = "ratio",
  group1 = ~cyl == 4,
  height = "50px")
```

### share
```{r}
kpiwidget(
  data = sd,
  column = "mpg",
  kpi = "sum",
  comparison = "share",
  group1 = ~cyl == 4,
  group2 = ~cyl == 6,
  height = "50px")
```

